import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFF7EC' },
  container: { flex: 1, backgroundColor: '#FFF7EC' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Platform.OS === 'ios' ? 20 : 15,
    paddingHorizontal: 10,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    position: 'relative',
  },
  headerTitle: {
    color: '#fff',
    fontSize: Platform.OS === 'ios' ? 22 : 20,
    fontWeight: 'bold',
  },
  logoutButton: {
    position: 'absolute',
    right: 15,
    top: 15,
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
    zIndex: 2,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#FFF',
    marginHorizontal: 10,
    marginTop: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  locationText: {
    flex: 1,
    color: '#F83600',
    fontSize: 14,
    marginRight: 8,
  },
  cameraList: {
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 80,
  },
  cameraCard: {
    backgroundColor: '#ccc',
    borderRadius: 10,
    marginBottom: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  cameraImage: { width: '100%', height: 200 },
  cameraLabel: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  bottomTabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 60,
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  tabItem: { alignItems: 'center', justifyContent: 'center' },
  tabText: { fontSize: 12, marginTop: 2, color: '#F83600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'center' },
  userManagementContainer: { flex: 1, backgroundColor: '#FFF7EC' },
  umHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Platform.OS === 'ios' ? 20 : 15,
    paddingHorizontal: 10,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    position: 'relative',
  },
  umHeaderTitle: { color: '#fff', fontSize: Platform.OS === 'ios' ? 22 : 20, fontWeight: 'bold' },
  umCloseButton: { position: 'absolute', right: 15, top: 15, padding: 10 },
  umContent: { padding: 16, paddingTop: 20 },
  noUserText: { fontSize: 16, color: '#555', textAlign: 'center', marginTop: 20 },
  userItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  userInfoContainer: { flex: 1 },
  userName: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  userInfo: { fontSize: 14, color: '#333' },
  deleteButton: {
    backgroundColor: '#EB5757',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  fingerprintContainer: { flex: 1, backgroundColor: '#FFF7EC' },
  fpHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Platform.OS === 'ios' ? 20 : 15,
    paddingHorizontal: 10,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    position: 'relative',
  },
  fpHeaderTitle: { color: '#fff', fontSize: Platform.OS === 'ios' ? 22 : 20, fontWeight: 'bold' },
  fpCloseButton: { position: 'absolute', right: 15, top: 15, padding: 10 },
  fpContent: { padding: 16, paddingTop: 20 },
  fpUserItem: {
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  fpUserName: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  fingerprintList: { marginTop: 8 },
  fingerprintItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#555',
    padding: 4,
    borderRadius: 4,
    marginBottom: 4,
  },
  fingerprintText: { color: '#fff', marginRight: 8 },
  fpActionButtons: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
  fpAddButton: {
    backgroundColor: '#4CAF50',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fpRemoveButton: {
    backgroundColor: '#EB5757',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  fingerprintInputModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fingerprintInputModal: { width: '80%', backgroundColor: '#fff', borderRadius: 12, padding: 16 },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 12, textAlign: 'center' },
  input: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 12 },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-around' },
  modalButton: { paddingVertical: 8, paddingHorizontal: 16, backgroundColor: '#F83600', borderRadius: 8 },
});

export default styles; 